version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      APP_ENV: prod
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
